config/routes.rb
Rails.application.routes.draw do
 

    resources :actus
    resources :apropos
    resources :contacts
    resources :publications

    	namespace :admin do
	  	resources :projets
	  	resources :users
      resources :publications

    end
 # 	resources :secteur
 # 	resources :pft
 #  resources :filiere

 	  namespace :super_admin do
      resources :publications
	    resources :users 
	    resources :projets
      resources :actus
      resources :tarifs
  	end
    
   root to: 'home#index'
   devise_for :users
   resources :projets
   get '/search' => 'projets#search', :as => 'search_projet'

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/projets_controller.rb
class Admin::ProjetsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_if_admin

    def index
      @projets = Projet.where(bailleur_id: current_user.id).order(:id).page(params[:page]).per(9)
    end

    def new
      @project = Projet.new 
    end
    def create
              @project = Projet.create!(nom_du_projet: params[:nom_du_projet],
                ptf_id: params[:ptf],
                appui_id: params[:appui],
                objectif_generale_du_projet: params[:objectif_generale_du_projet],
                aspsp: params[:aspsp],comment: params[:comment],
                debut_du_projet: params[:debut_du_projet].to_date,
                fin: params[:fin].to_date, siteweb: params[:site],
                bailleur_id: current_user.id)

                if params[:creer] == 'Enregistrer'
                    @project.update(validation: nil)

                end

                for x in 1..Secteur.all.count
                  case params[:"unite_id#{x}"]
                    when "1"
                      @montant = params[:"montant#{x}"]
                      @convert_usd = @montant
                    when "2"
                      @montant = params[:"montant#{x}"]
                      @uac = Tarif.where(unite_id:  2, reference: "UAC").last.valeur
                      @convert_uac = @montant.to_i / @uac
                      @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
                      @convert_usd = @convert_uac * @usd
                    when "3"
                      @montant = params[:"montant#{x}"]
                      @convert_uac = @montant.to_i
                      @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
                      @convert_usd = @convert_uac * @usd

                  end
                  if params[:"montant#{x}"].to_i > 0
                    Montant.create(price: @convert_usd.to_i,secteur_id: x, projet_id: @project.id, unite_id: 1)
                  end
                end
                     
                  @secteur_ids = params[:secteur_ids]
                @secteur_ids.each do |x|
                  Secteurprojet.create(projet_id: @project.id , secteur_id: x.to_i)
                end

                if params[:filiere_ids]
                  @filiere_ids = params[:filiere_ids]
                @filiere_ids.each do |x|
                  Filiereprojet.create(projet_id: @project.id , filiere_id: x.to_i)
                end
                end

                if params[:forme_ids]
                  @forme_ids = params[:forme_ids]
                @forme_ids.each do |x|
                  Formeprojet.create(projet_id: @project.id , forme_id: x.to_i)
                end
                end

                for x in 1..2
                  if params[:"partONG#{x}"]
                    @partenaire = Partenaire.create(plateforme: "ONG", description: params[:"desc_partONG#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end
                  if params[:"partASS#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Associations", description: params[:"desc_partASS#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partPRI#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Secteurs Privés", description: params[:"desc_partPRI#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partCOM#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Chambres de Commerce", description: params[:"desc_partCOM#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partAUTRE#{x}"]
                    @partenaire = Partenaire.create(plateforme: params[:"plat_partAUTRE#{x}"], description: params[:"desc_partAUTRE#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                end
                  
                if params[:iga_ids]
                  
                  @iga_ids = params[:iga_ids]
                @iga_ids.each do |i|
                  Igaprojet.create(projet_id: @project.id , iga_id: i.to_i) 
                end
                end


                if params[:zone_ids]
                  @zone_ids = params[:zone_ids]
                @zone_ids.each do |z|
                  Zoneprojet.create(projet_id: @project.id , zone_id: z.to_i)
                end
                end

                10.times do |x|
                  if params[:"checkben#{x}"] && params[:newben] != ""
                    @ben = Beneficiaire.create(title: params[:"valben#{x}"])
                    Benefprojet.create(projet_id: @project.id , beneficiaire_id: @ben.id)
                  end
                end
                if params[:beneficiaire_ids]
                  @beneficiaire_ids = params[:beneficiaire_ids]
                @beneficiaire_ids.each do |b|
                  Benefprojet.create(projet_id: @project.id , beneficiaire_id: b.to_i)
                end
                end

                if params[:pem_ids]
                @pem_ids = params[:pem_ids]
                @pem_ids.each do |p|
                  Pemprojet.create(projet_id: @project.id , pem_id: p.to_i)
                end
                end

          if @project.save
            @project.files.attach(params[:files])
            @project.picture.attach(params[:picture])
            redirect_to admin_projets_path, success: "Projet créé avec succès. Un email de validation vous a été envoyé, veuillez consulter votre boite de reception"
          else
            render :new

          end           
     end

  def show
    @projet = Projet.find(params[:id])
    if params[:creer] == 'Publier'
      @project.update(validation: false)

    end
  end

  def edit
    @projet = Projet.find(params[:id])
    @secteurprojets = Secteurprojet.where(projet_id: @projet.id)
    @sects = []
    @secteurprojets.each do |sp|
      @sects << sp.secteur
    end

    @filiereprojets = Filiereprojet.where(projet_id: @projet.id)
    @fils = []
    @filiereprojets.each do |fp|
      @fils << fp.filiere
    end


    @formprojets = Formeprojet.where(projet_id: @projet.id)
    @forms = []
    @formprojets.each do |fop|
      @forms << fop.forme
    end

    @beneficiaireprojets = Benefprojet.where(projet_id: @projet.id)
    @bens = []
    @beneficiaireprojets.each do |bp|
      @bens << bp.beneficiaire
    end

    @igaprojets = Igaprojet.where(projet_id: @projet.id)
    @igas = []
    @igaprojets.each do |ip|
      @igas << ip.iga
    end

    @zoneprojets = Zoneprojet.where(projet_id: @projet.id)
    @zones = []
    @zoneprojets.each do |zp|
      @zones << zp.zone
    end

  end

  def update
    @projet = Projet.find(params[:id])
    if @projet.update(nom_du_projet: params[:nom_du_projet], 
     debut_du_projet: params[:debut_du_projet].to_date,
      objectif_generale_du_projet: params[:objectif_generale_du_projet],
     aspsp: params[:aspsp],fin: params[:fin].to_date, 
     appui_id: params[:appui], ptf_id: params[:ptf], 
     bailleur_id: current_user.id)

    if params[:modifier] == 'Publier' || params[:modifier] == 'Re-publier'
      @projet.update(validation: false)

    end

    @projet.secteurprojets.destroy_all
    @projet.montants.destroy_all

    for x in 0..Secteur.all.count

      case params[:"unite_id#{x}"]
        when "1"
          @montant = params[:"montant#{x}"]
          @convert_usd = @montant
        when "2"
          @montant = params[:"montant#{x}"]
          @uac = Tarif.where(unite_id:  2, reference: "UAC").last.valeur
          @convert_uac = @montant.to_i / @uac
          @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
          @convert_usd = @convert_uac * @usd
        when "3"
          @montant = params[:"montant#{x}"]
          @convert_uac = @montant.to_i
          @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
          @convert_usd = @convert_uac * @usd

      end
      if params[:"secteur_#{x}"]
        Secteurprojet.create(projet_id: @projet.id, secteur_id: params[:"secteur_#{x}"])
        # Montant.create(price: params[:"montant#{params[:"secteur_#{x}"]}"],secteur_id: params[:"secteur_#{x}"], projet_id: @projet.id, unite_id: params[:"unite_id#{params[:"secteur_#{x}"]}"])
        Montant.create(price: @convert_usd.to_i,secteur_id: params[:"secteur_#{x}"], projet_id: @projet.id, unite_id: 1)
      end
    end


    @projet.filiereprojets.destroy_all
    params[:filiere_ids].each do |filiere_id|
        Filiereprojet.create(projet_id: @projet.id, filiere_id: filiere_id.to_i)
    end

     @projet.formeprojets.destroy_all
    params[:forme_ids].each do |forme_id|
        Formeprojet.create(projet_id: @projet.id, forme_id: forme_id.to_i)
    end



    @projet.benefprojets.destroy_all
    for x in 0..Beneficiaire.all.count-1
      if params[:"beneficiaire_#{x}"]
        Benefprojet.create(projet_id: @projet.id, beneficiaire_id: params[:"beneficiaire_#{x}"])
      end
    end

    @projet.igaprojets.destroy_all
    for x in 0..Iga.all.count-1
      if params[:"iga_#{x}"]
        Igaprojet.create(projet_id: @projet.id, iga_id: params[:"iga_#{x}"])
      end
    end


    @projet.zoneprojets.destroy_all
    for x in 0..Zone.all.count-1
      if params[:"zone_#{x}"]
        Zoneprojet.create(projet_id: @projet.id, zone_id: params[:"zone_#{x}"])
      end
    end
    redirect_to  admin_projet_path, success: "Modification terminée"
  else
    puts 'erreur'*10
    render :edit     
  end
end

def destroy
  @projet = Projet.find(params[:id])
  @projet.destroy
  redirect_to admin_projets_path
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  
    def index
  
        if params[:search]
          if params[:search] == nil
              redirect_to(root_path)
          else  
            @parameter = params[:search].downcase  
            @res = Projet.where(validation: true) 
            @results = @res.where("lower(nom_du_projet) LIKE :search", search: "%#{@parameter}%")
          end  
      end

    end
  
    def show
      @projet = Projet.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf { 
          render :pdf => "show", :layout => 'pdf.html'
        }
      end
    end  
  end

app/controllers/super_admin/actus_controller.rb
class SuperAdmin::ActusController < ApplicationController
  before_action :authenticate_user!

  def create

      @user = User.where(is_super_admin: true)
      @actu = Actu.create!(title: params[:title], user_id: current_user.id)

      if @actu.save
       @actu.files.attach(params[:files])
       redirect_to super_admin_actus_path, success: "Actualité créée avec succès"
     else
       render :new

     end 


  end

  def new
    @actus = Actu.order(:id).page(params[:page]).per(9)
  end

  def index
    @actus = Actu.order(:id).page(params[:page]).per(9)
  end

   def show
     @actu = Actu.find(params[:id])
   end

   def edit
     @actu = Actu.find(params[:id])
   end

  def update
      @actu = Actu.find(params[:id])
      if @actu.update(title: params[:title], user_id: current_user.id)
       redirect_to super_admin_actus_path, succès: "Modification terminée"
     end
  end

  def destroy
    @actu = Actu.find(params[:id])
    @actu.destroy
    redirect_to super_admin_actus_path
  end

end

app/controllers/super_admin/projets_controller.rb
class SuperAdmin::ProjetsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_if_super_admin

  def index
  	@projets = Projet.where(validation: false).order(:id).page(params[:page]).per(9)
    @projets_valides = Projet.where(validation: true).order(:id).page(params[:page]).per(9)
  end

  def show
    @projet = Projet.find(params[:id])
  end

  def update
  	@projet = Projet.find(params[:id])
   	@projet.update(validation: true)
   	redirect_to super_admin_projets_path, success: "Projet validé"
  end

  def destroy
  	@projet = Projet.find(params[:id])
  	@projet.destroy
  	redirect_to super_admin_projets_path
  end

  def check_if_super_admin
      if current_user.is_super_admin == false
        redirect_to root_path
      end
  end
end

app/controllers/super_admin/publications_controller.rb
class SuperAdmin::PublicationsController < ApplicationController
	before_action :authenticate_user!

	def create
	  	@pub = Publication.create!(title: params[:title], description: params[:description], user_id: current_user.id)

	    	if @pub.save
	    		@pub.files.attach(params[:files])
	            redirect_to publications_path, success: "Publication créée avec succès"
	        else
	            render :new

	        end  
	end
	def edit
	   @pub = Publication.find(params[:id]) 	
	end    
	def update
		@pub = Publication.find(params[:id])

    	if @pub.update(title: params[:title], description: params[:description],user_id: current_user.id)
       		redirect_to super_admin_publications_path, success: "Modification terminéé"
	   	end
		
	end 
	def destroy
	  @pub = Publication.find(params[:id])
	  @pub.destroy
	  redirect_to super_admin_publications_path
		
	end
	def index
		@pubs = Publication.order(:id).page(params[:page]).per(9)
	end
	def show
		@pub = Publication.find(params[:id])
		
	end
end

app/controllers/super_admin/tarifs_controller.rb
class SuperAdmin::TarifsController < ApplicationController
	before_action :authenticate_user!
  def index
  end

  def edit
    @tarif = Tarif.find(params[:id])
  end

  def update
      @tarif = Tarif.find(params[:id])
      if @tarif.update(reference: params[:reference], valeur: params[:valeur], unite_id: params[:unite])

        if params[:cree] == 'À utiliser'
          @tarif.update(utilise: true)

        end
        redirect_to edit_super_admin_tarif_path(@tarif.id), success: "Taux de change modifié!!"
      else
        render :new

      end  
  end

  def new
  	@tarif = Tarif.new
  end

  def create
	  	@tarif = Tarif.create!(reference: params[:reference], valeur: params[:valeur], unite_id: params[:unite])
        if params[:cree] == 'A utiliser'
          @tarif.update(utilise: true)

        end
		  if @tarif.save
		    redirect_to new_super_admin_tarif_path, success: "Taux de change créé!!"
		  else
		    render :new

		  end  
  end

  def destroy
    @tarif = Tarif.find(params[:id])
      @tarif.destroy
    redirect_to super_admin_tarifs_path, danger:"Taux supprimé"
  end

end

app/controllers/super_admin/users_controller.rb
class SuperAdmin::UsersController < ApplicationController
 	before_action :authenticate_user!
	before_action :check_if_super_admin


	def index
		@users = User.where(is_admin: true).or(User.where(is_consultant: true))
		@users_en_attente = User.where(is_consultant: false,is_super_admin: false,is_admin: nil)
		
		@users.each do |u|
			@u = u
			u.messages.each do |m|
				@message_id = m.id
			end
		end	
	end


	def show
		@user = User.find(params[:id])
	end

	def check_if_super_admin
	    if current_user.is_super_admin == false
	      redirect_to root_path
	    end
 	end

 	

 	def update
 		@user = User.find(params[:id])
 		if buttonparams == 'Consultant'
 			@user.update(is_consultant: true)
 		else
 			@user.update(is_admin: true)
 		end

 		# if @user.is_consultant == false
 		# 	@user.update(is_consultant: true)
 		# if @user.is_admin == false
 		# 	@user.update(is_admin: true)
 		# end
 		redirect_to super_admin_users_path
 	end

 	def destroy
 		@user = User.find(params[:id])
 		@messages = Message.where(sender_id: @user.id)
 		@projets = Projet.where(bailleur_id: @user.id)
 		@publications = Publication.where(user_id: @user.id)
 		@user.destroy
 		
 		redirect_to super_admin_users_path
 	end

 	private 

 	def buttonparams
 		params[:valider]
 	end
end

app/helpers/projet_helper.rb
module ProjetHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/helpers/super_admin/actus_helper.rb
module SuperAdmin::ActusHelper
end

app/helpers/super_admin/projets_helper.rb
module SuperAdmin::ProjetsHelper
end

app/helpers/super_admin/tarifs_helper.rb
module SuperAdmin::TarifsHelper
end

app/helpers/super_admin/users_helper.rb
module SuperAdmin::UsersHelper
end

app/views/super_admin/projets/index.html.erb
<%if @projets.count == 0 %>
	<div class="container sans-head mb-5">
		<div class="text-center text-muted mt-4 mb-4">
			<p> Rien à valider </p>
		</div>
	</div>

<%else%>

<div class="container sans-head mb-5">
	<div class="text-center text-muted mt-4 mb-4 ">
		<p> Projets validés </p>
	</div>
	<div class="row justify-content-center">
		<% @projets_valides.each do |p|%>
			<div class="col-md-3 mb-2 card mx-1 position-relative">
				<div class="card-body">
			 	 	<div class="card-title table">
				    	<h6><%= p.nom_du_projet %></h6>
				    </div>
					<div class="card-text">
						<p class="card-text text-muted mb-5 truncate-pub"><%= raw p.objectif_generale_du_projet.truncate(100) %></p>
					</div>
				    <p class="mt-3 position-absolute more-info-pub"><a href="<%= super_admin_projet_path(p.id)%>" class="btn-forgot underline">Voir</a></p>
				</div>
			</div>
		<%end%>	
	</div>
	<div class="text-center">
		<%= paginate @projets_valides %>
	</div>
</div>



<div class="container sans-head mb-5">
	<div class="text-center text-muted mt-4 mb-4 ">
		<p> Projets en attente de validation </p>
	</div>
	<div class="row justify-content-center">
		<% @projets.each do |p|%>
			<div class="col-md-3 mb-2 card mx-1 position-relative">
				<div class="card-body">
			 	 	<div class="card-title table">
				    	<h6><%= p.nom_du_projet %></h6>
				    </div>
					<div class="card-text">
						<p class="card-text text-muted mb-5 truncate-pub"><%= raw p.objectif_generale_du_projet.truncate(100) %></p>
					</div>
				    <p class="mt-3 position-absolute more-info-pub"><a href="<%= super_admin_projet_path(p.id)%>" class="btn-forgot underline">Voir</a></p>
				</div>
			</div>
		<%end%>	
	</div>
	<div class="text-center">
		<%= paginate @projets %>
	</div>
</div>
<%end%>

app/views/super_admin/projets/show.html.erb
<header class="aci59a-0 eyAIuG sticky-limit">
    <div class="sc-1gnwgfb-2 hVIPFV pict">
      <style type="text/css">
        .pict {
           <%if @projet.secteurprojets.count == 1%>
            <%@projet.secteurprojets.each do|sp|%>
              background-image: url('/<%=sp.secteur.image_url%>');
            <%end%>
          <%else%>
            background-image: url('/secteur/accueil.jpg');
          <%end%>
        }

      </style>  
    </div>
</header>
  <div class="logo">
    <div class="pic">
      <div class="imge-rep d-flex align-items-center justify-content-center">
        <%if @projet.ptf.image_url%>
          <img src="/<%= @projet.ptf.image_url%>">
        <%end%>
      </div>
    </div>
    <div class="d-flex align-items-center h-text">
      <div class="text-white pr-4">
        <h3><%=@projet.nom_du_projet%></h3>
      </div>
    </div>
    <div class="asi"> 
      <div class="aside">
          <% if  @projet.secteurprojets.count == 1%>
              <p><span class="attr">Secteur : </span>
          <%else%>
              <p><span class="attr">Secteurs : </span>
          <%end%>
            <span class="word">
              <%@projet.secteurprojets .each do|sp|%>
                  <% if sp == @projet.secteurprojets.last%>
                    <span><%=sp.secteur.title %></span>
                  <% else %>
                    <span><%=sp.secteur.title %>, </span>
                  <% end %>
              <% end %>
              
            </span>
          </p>
       
         <% if  @projet.formeprojets.count == 1%>
              <p><span class="attr">Forme d'appui : </span>
          <%else%>
              <p><span class="attr">Formes d'appui : </span>
          <%end%>
          <span class="word">
              <%@projet.formeprojets .each do|fop|%>
                <% if fop == @projet.formeprojets.last%>
                  <span><%=fop.forme.title %></span>
                <% else %>
                  <span><%=fop.forme.title %>, </span>
                <% end %>
              <% end %>
            
          </span>
          </p>
        
          <% if  @projet.filiereprojets.count == 1%>
              <p><span class="attr">Filière : </span>
          <%else%>
              <p><span class="attr">Filières : </span>
          <%end%>
          <span class="word">
              <%@projet.filiereprojets .each do|fp|%>
                <% if fp == @projet.filiereprojets.last%>
                  <span><%=fp.filiere.title %></span>
                <% else %>
                  <span><%=fp.filiere.title %>, </span>
                <% end %>
              <% end %>
            
          </span>
          </p>
      </div>
    </div>
  </div>
  <div class="show-cont pt-4 pb-4">
    <div class="objectif mx-auto">
      <h2 class="text-left color">Objectif général du projet</h2>
      <div class="mt-2 pt-2">
        <%= raw @projet.objectif_generale_du_projet%>
      </div>
      <div class="appui mt-4">
        <h2 class="color text-left">Appui spécifique au secteur privé</h2>
        <div class="p-2">
          <%= raw @projet.aspsp%>
        </div>
      </div>
      <div class="row pt-4 pb-4">
        <div class="col-md-6 list">

          <% if  @projet.igaprojets.count == 1%>
            <p><span class="attr">Institution Gouvernementale Associée : </span></p>
          <%else%>
            <p><span class="attr">Institutions Gouvernementales Associées : </span></p>
          <%end%>
          <div class="mb-3">
              <%@projet.igaprojets .each do|g|%>
                  <%if g == @projet.igaprojets.last%>
                    <span><%=g.iga.title %></span>
                  <% else %>
                    <span><%=g.iga.title %>, </span>
                  <% end %>
              <% end %>
          </div>

          <% if  @projet.zoneprojets.count == 1%>
              <p><span class="attr">Région : </span></p>
          <%else%>
              <p><span class="attr">Régions : </span></p>
          <%end%>
          <div class="mb-3">
              <%@projet.zoneprojets.each do|zp|%>
                <% if zp == @projet.zoneprojets.last%>
                  <span><%=zp.zone.title %></span>
                <%else%>
                  <span><%=zp.zone.title %>, </span>
                <% end %>
              <% end %>
          </div>
          
          <% if  @projet.partenaireprojets.count == 1%>
              <p><span class="attr">Partenaire d'implémentation : </span></p>
          <%else%>
              <p><span class="attr">Partenaires d'implémentations : </span></p>
          <%end%>
          <div class="mb-3">
              <%@projet.partenaireprojets .each do|pap|%>
                <% if pap == @projet.partenaireprojets.last%>
                  <span><%=pap.partenaire.plateforme %></span>
                <%else%>
                  <span><%=pap.partenaire.plateforme %>, </span>
                <% end %>
              <% end %>
          </div>

          <% if  @projet.benefprojets.count == 1%>
              <p><span class="attr">Bénéficiaire : </span></p>
          <%else%>
              <p><span class="attr">Bénéficiaires : </span></p>
          <%end%>
          <div class="mb-3">
              <%@projet.benefprojets.each do|ben|%>
                  <%if ben == @projet.benefprojets.last%>
                    <span><%=ben.beneficiaire.title %></span>
                  <% else %>
                    <span><%=ben.beneficiaire.title %>, </span>
                  <% end %>
              <% end %>
          </div>

          <% @projet.montants.each do |m|%>
            <p><span class="attr">Montant  pour le secteur <%= m.secteur.title.downcase%> :</span>
                <p class="mb-3"><%= m.price %> <%= m.unite.nom%></p>
            </p>

          <%end%>
        </div>
        <div class="col-md-6 list">
          <p class="mb-3"><span class="attr">Nature de l'appui : </span><%=@projet.appui.title%></p>
          <p class="mb-3"><span class="attr">Début : </span><%=@projet.debut_du_projet%> &nbsp;&nbsp;&nbsp;&nbsp;<span class="attr">Fin : </span><%=@projet.fin%></p>
          <p><span class="attr">Alignement aux priorités du plan Emergence de Madagascar : </span><p>
          <div  class="mb-3">
            <% @projet.pemprojets.each do |p|%>
                <p> <%=p.pem.title%></p>
            <%end%>
          </div>

          <%if @projet.siteweb == " "%>
            <p class="mb-3"><span class="attr">Site web : </span>
                <span class="word">
                  <a href="https://<%= @projet.siteweb.remove('https://')%>"><%= @projet.siteweb%></a>
                </span>
            </p>
          <%end%>

          <%if @projet.files.attached?%>
            <%@projet.files.each do|file|%> 
            <p><span class="attr">Fichier : </span><%= link_to file.filename, rails_blob_path(file, disposition: "attachement") %></p>
            <%end%>
        <%end%>
       
        </div>
    </div>
    <div class="text-right">
      <a href="<%= super_admin_projet_path(@projet.id)%>" class="sc-eerKOB cfnPHQ bold sear" data-method="put">Valider</a>
      <a href="<%= super_admin_projet_path(@projet.id)%>" class="btn btn-danger" data-confirm="Voulez-vous refusez ce projet ?">Annuler</a>
    </div>