config/routes.rb
Rails.application.routes.draw do
 

    resources :actus
    resources :apropos
    resources :contacts
    resources :publications

    	namespace :admin do
	  	resources :projets
	  	resources :users
      resources :publications

    end
 # 	resources :secteur
 # 	resources :pft
 #  resources :filiere

 	  namespace :super_admin do
      resources :publications
	    resources :users 
	    resources :projets
      resources :actus
      resources :tarifs
  	end
    
   root to: 'home#index'
   devise_for :users
   resources :projets
   get '/search' => 'projets#search', :as => 'search_projet'

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/projet.rb
class Projet < ApplicationRecord
        validates :objectif_generale_du_projet, presence: true
        validates :aspsp, presence: true
        
        belongs_to :bailleur, optional: true, class_name: 'User'
        belongs_to :ptf, optional: true
        belongs_to :appui, optional: true
        has_many :montants
# relation de table entre projet et secteur a travers benefprojet
        has_many :benefprojets
        has_many :beneficiaires, through: :benefprojets
   
# relation de table entre projet et secteur a travers zoneprojet
        has_many :zoneprojets
        has_many :zones, through: :zoneprojets
       
        # relation de table entre projet et secteur a travers igaprojets
        has_many :igaprojets
        has_many :igas, through: :igaprojets
      
     # relation de table entre projet et secteur a travers filiereprojets
        has_many :filiereprojets
        has_many :filieres, through: :filiereprojets
        

        # relation de table entre projet et secteur a travers secteurprojet

        has_many :secteurprojets 
        has_many :secteurs, through: :secteurprojets
    

        has_many :pemprojets
        has_many :pems, through: :pemprojets

        has_many :formeprojets
        has_many :formes, through: :formeprojets

        has_many :partenaireprojets
        has_many :partenaires, through: :partenaireprojets
    
        
        has_many_attached :files
        has_one_attached :picture
       

        after_create :create_project_send

        # This method calls the order_email method from user_mailer, passing the order as an argument
        def create_project_send
            UserMailer.create_project_email(self).deliver_now
        end

end

app/controllers/admin/projets_controller.rb
class Admin::ProjetsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_if_admin

    def index
      @projets = Projet.where(bailleur_id: current_user.id).order(:id).page(params[:page]).per(9)
    end

    def new
      @project = Projet.new 
    end
    def create
              @project = Projet.create!(nom_du_projet: params[:nom_du_projet],
                ptf_id: params[:ptf],
                appui_id: params[:appui],
                objectif_generale_du_projet: params[:objectif_generale_du_projet],
                aspsp: params[:aspsp],comment: params[:comment],
                debut_du_projet: params[:debut_du_projet].to_date,
                fin: params[:fin].to_date, siteweb: params[:site],
                bailleur_id: current_user.id)

                if params[:creer] == 'Enregistrer'
                    @project.update(validation: nil)

                end

                for x in 1..Secteur.all.count
                  case params[:"unite_id#{x}"]
                    when "1"
                      @montant = params[:"montant#{x}"]
                      @convert_usd = @montant
                    when "2"
                      @montant = params[:"montant#{x}"]
                      @uac = Tarif.where(unite_id:  2, reference: "UAC").last.valeur
                      @convert_uac = @montant.to_i / @uac
                      @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
                      @convert_usd = @convert_uac * @usd
                    when "3"
                      @montant = params[:"montant#{x}"]
                      @convert_uac = @montant.to_i
                      @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
                      @convert_usd = @convert_uac * @usd

                  end
                  if params[:"montant#{x}"].to_i > 0
                    Montant.create(price: @convert_usd.to_i,secteur_id: x, projet_id: @project.id, unite_id: 1)
                  end
                end
                     
                  @secteur_ids = params[:secteur_ids]
                @secteur_ids.each do |x|
                  Secteurprojet.create(projet_id: @project.id , secteur_id: x.to_i)
                end

                if params[:filiere_ids]
                  @filiere_ids = params[:filiere_ids]
                @filiere_ids.each do |x|
                  Filiereprojet.create(projet_id: @project.id , filiere_id: x.to_i)
                end
                end

                if params[:forme_ids]
                  @forme_ids = params[:forme_ids]
                @forme_ids.each do |x|
                  Formeprojet.create(projet_id: @project.id , forme_id: x.to_i)
                end
                end

                for x in 1..2
                  if params[:"partONG#{x}"]
                    @partenaire = Partenaire.create(plateforme: "ONG", description: params[:"desc_partONG#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end
                  if params[:"partASS#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Associations", description: params[:"desc_partASS#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partPRI#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Secteurs Privés", description: params[:"desc_partPRI#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partCOM#{x}"]
                    @partenaire = Partenaire.create(plateforme: "Chambres de Commerce", description: params[:"desc_partCOM#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                  if params[:"partAUTRE#{x}"]
                    @partenaire = Partenaire.create(plateforme: params[:"plat_partAUTRE#{x}"], description: params[:"desc_partAUTRE#{x}"])
                    Partenaireprojet.create(projet_id: @project.id , partenaire_id: @partenaire.id)
                  end

                end
                  
                if params[:iga_ids]
                  
                  @iga_ids = params[:iga_ids]
                @iga_ids.each do |i|
                  Igaprojet.create(projet_id: @project.id , iga_id: i.to_i) 
                end
                end


                if params[:zone_ids]
                  @zone_ids = params[:zone_ids]
                @zone_ids.each do |z|
                  Zoneprojet.create(projet_id: @project.id , zone_id: z.to_i)
                end
                end

                10.times do |x|
                  if params[:"checkben#{x}"] && params[:newben] != ""
                    @ben = Beneficiaire.create(title: params[:"valben#{x}"])
                    Benefprojet.create(projet_id: @project.id , beneficiaire_id: @ben.id)
                  end
                end
                if params[:beneficiaire_ids]
                  @beneficiaire_ids = params[:beneficiaire_ids]
                @beneficiaire_ids.each do |b|
                  Benefprojet.create(projet_id: @project.id , beneficiaire_id: b.to_i)
                end
                end

                if params[:pem_ids]
                @pem_ids = params[:pem_ids]
                @pem_ids.each do |p|
                  Pemprojet.create(projet_id: @project.id , pem_id: p.to_i)
                end
                end

          if @project.save
            @project.files.attach(params[:files])
            @project.picture.attach(params[:picture])
            redirect_to admin_projets_path, success: "Projet créé avec succès. Un email de validation vous a été envoyé, veuillez consulter votre boite de reception"
          else
            render :new

          end           
     end

  def show
    @projet = Projet.find(params[:id])
    if params[:creer] == 'Publier'
      @project.update(validation: false)

    end
  end

  def edit
    @projet = Projet.find(params[:id])
    @secteurprojets = Secteurprojet.where(projet_id: @projet.id)
    @sects = []
    @secteurprojets.each do |sp|
      @sects << sp.secteur
    end

    @filiereprojets = Filiereprojet.where(projet_id: @projet.id)
    @fils = []
    @filiereprojets.each do |fp|
      @fils << fp.filiere
    end


    @formprojets = Formeprojet.where(projet_id: @projet.id)
    @forms = []
    @formprojets.each do |fop|
      @forms << fop.forme
    end

    @beneficiaireprojets = Benefprojet.where(projet_id: @projet.id)
    @bens = []
    @beneficiaireprojets.each do |bp|
      @bens << bp.beneficiaire
    end

    @igaprojets = Igaprojet.where(projet_id: @projet.id)
    @igas = []
    @igaprojets.each do |ip|
      @igas << ip.iga
    end

    @zoneprojets = Zoneprojet.where(projet_id: @projet.id)
    @zones = []
    @zoneprojets.each do |zp|
      @zones << zp.zone
    end

  end

  def update
    @projet = Projet.find(params[:id])
    if @projet.update(nom_du_projet: params[:nom_du_projet], 
     debut_du_projet: params[:debut_du_projet].to_date,
      objectif_generale_du_projet: params[:objectif_generale_du_projet],
     aspsp: params[:aspsp],fin: params[:fin].to_date, 
     appui_id: params[:appui], ptf_id: params[:ptf], 
     bailleur_id: current_user.id)

    if params[:modifier] == 'Publier' || params[:modifier] == 'Re-publier'
      @projet.update(validation: false)

    end

    @projet.secteurprojets.destroy_all
    @projet.montants.destroy_all

    for x in 0..Secteur.all.count

      case params[:"unite_id#{x}"]
        when "1"
          @montant = params[:"montant#{x}"]
          @convert_usd = @montant
        when "2"
          @montant = params[:"montant#{x}"]
          @uac = Tarif.where(unite_id:  2, reference: "UAC").last.valeur
          @convert_uac = @montant.to_i / @uac
          @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
          @convert_usd = @convert_uac * @usd
        when "3"
          @montant = params[:"montant#{x}"]
          @convert_uac = @montant.to_i
          @usd = Tarif.where(unite_id:  1, reference: "UAC").last.valeur
          @convert_usd = @convert_uac * @usd

      end
      if params[:"secteur_#{x}"]
        Secteurprojet.create(projet_id: @projet.id, secteur_id: params[:"secteur_#{x}"])
        # Montant.create(price: params[:"montant#{params[:"secteur_#{x}"]}"],secteur_id: params[:"secteur_#{x}"], projet_id: @projet.id, unite_id: params[:"unite_id#{params[:"secteur_#{x}"]}"])
        Montant.create(price: @convert_usd.to_i,secteur_id: params[:"secteur_#{x}"], projet_id: @projet.id, unite_id: 1)
      end
    end


    @projet.filiereprojets.destroy_all
    params[:filiere_ids].each do |filiere_id|
        Filiereprojet.create(projet_id: @projet.id, filiere_id: filiere_id.to_i)
    end

     @projet.formeprojets.destroy_all
    params[:forme_ids].each do |forme_id|
        Formeprojet.create(projet_id: @projet.id, forme_id: forme_id.to_i)
    end



    @projet.benefprojets.destroy_all
    for x in 0..Beneficiaire.all.count-1
      if params[:"beneficiaire_#{x}"]
        Benefprojet.create(projet_id: @projet.id, beneficiaire_id: params[:"beneficiaire_#{x}"])
      end
    end

    @projet.igaprojets.destroy_all
    for x in 0..Iga.all.count-1
      if params[:"iga_#{x}"]
        Igaprojet.create(projet_id: @projet.id, iga_id: params[:"iga_#{x}"])
      end
    end


    @projet.zoneprojets.destroy_all
    for x in 0..Zone.all.count-1
      if params[:"zone_#{x}"]
        Zoneprojet.create(projet_id: @projet.id, zone_id: params[:"zone_#{x}"])
      end
    end
    redirect_to  admin_projet_path, success: "Modification terminée"
  else
    puts 'erreur'*10
    render :edit     
  end
end

def destroy
  @projet = Projet.find(params[:id])
  @projet.destroy
  redirect_to admin_projets_path
end

app/controllers/projets_controller.rb
class ProjetsController < ApplicationController
  
    def index
  
        if params[:search]
          if params[:search] == nil
              redirect_to(root_path)
          else  
            @parameter = params[:search].downcase  
            @res = Projet.where(validation: true) 
            @results = @res.where("lower(nom_du_projet) LIKE :search", search: "%#{@parameter}%")
          end  
      end

    end
  
    def show
      @projet = Projet.find(params[:id])
      respond_to do |format|
        format.html
        format.pdf { 
          render :pdf => "show", :layout => 'pdf.html'
        }
      end
    end  
  end

app/controllers/super_admin/projets_controller.rb
class SuperAdmin::ProjetsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_if_super_admin

  def index
  	@projets = Projet.where(validation: false).order(:id).page(params[:page]).per(9)
    @projets_valides = Projet.where(validation: true).order(:id).page(params[:page]).per(9)
  end

  def show
    @projet = Projet.find(params[:id])
  end

  def update
  	@projet = Projet.find(params[:id])
   	@projet.update(validation: true)
   	redirect_to super_admin_projets_path, success: "Projet validé"
  end

  def destroy
  	@projet = Projet.find(params[:id])
  	@projet.destroy
  	redirect_to super_admin_projets_path
  end

  def check_if_super_admin
      if current_user.is_super_admin == false
        redirect_to root_path
      end
  end
end

app/helpers/projet_helper.rb
module ProjetHelper
end

app/helpers/projets_helper.rb
module ProjetsHelper
end

app/helpers/super_admin/projets_helper.rb
module SuperAdmin::ProjetsHelper
end

app/views/projets/edit.html.erb
<%= form_tag url_for(action: "update"), method: "put" do |f| %>
  <%= label_tag 'nom_du_projet' %>  
    
<% end %>

app/views/projets/new.html.erb
  <header class="aci59a-0 eyAIuG haute sticky-limit">
    <div class="sc-1gnwgfb-2 stom">
    </div>
  </header>
<div class="mt-4 mb-4">
	<%= form_tag url_for(action: 'create'),method:'post', class:'form' do%>
		<div class="container">
			<div class="row mb-2">
				<div class="col-6">
					<div>
						<label for="nom" class="mr-2 table">Nom du projet </label>
					</div>
					<input type="text" name="nom_du_projet" id="nom" placeholder="Nom du projet" class="form-control">
				</div>
			</div>
			<div class="d-flex justify-content-between mb-3">
				<div>
					<h6 class="table">PTF</h6>
					<%= select_tag 'ptf_id', options_for_select(Ptf.all.collect{ |c| [c.title, c.id] }), :include_blank => "choisir", class: "form-control"%>
				</div>
				<div>
					<h6 class="table">Début</h6>
					<input type="date" name="debut_du_projet" class="form-control">
				</div>
				<div>
					<h6 class="table">Fin</h6>
					<input type="date" name="fin" class="form-control">
				</div>
				<div>
					<h6 class="table">Montant</h6>
					  <input name="montant" type = "range" min="0" max="60" onchange="rangevalue.value=value"/>
                  <output id="rangevalue">0</output> 
				</div>
				<div>
					<h6 class="table">Apui</h6>
					<%= select_tag 'appui_id', options_for_select(Appui.all.collect{ |c| [c.title, c.id] }), :include_blank => "choisir", class: "form-control"%>
				</div>
			</div>
		</div>

		<div class="container mb-2">
			<a class="btn-col" data-toggle="collapse" href="#secteur" role="button" aria-expanded="false" aria-controls="collapseExample">
				secteur
			</a>
				<div class="collapse" id="secteur">
				<div class="card card-body">
					<div class="row">
						<% Secteur.all.each do |c| %>
							<div class="col-md-4">
								<%= check_box("secteur_id",c.id, {checked: false}, {class: "form-control"}) %>
								<%=h c.title%>
							</div> 
						<% end %>
					</div>
				</div>
				</div>
			</div>



			<div class="container mb-2">
			<a class="btn-col" data-toggle="collapse" href="#filiere" role="button" aria-expanded="false" aria-controls="collapseExample">
				Filiere
			</a>
				<div class="collapse" id="filiere">
				<div class="card card-body">
					<div class="row">
						<% Filiere.all.each do |c| %>
							<div class="col-md-3">
								<%= check_box("filiere_id",c.id, {checked: false}) %>
								<%=h c.title%>
							</div>
						<% end %>
					</div>
				</div>
				</div>
			</div>

			<div class="container mb-2">
				<a class="btn-col" data-toggle="collapse" href="#Beneficiaire" role="button" aria-expanded="false" aria-controls="collapseExample">
					Beneficiaire
				</a>
				<div class="collapse" id="Beneficiaire">
					<div class="card card-body">
						<div class="row">
							<% Beneficiaire.all.each do |c| %>
								<div class="col-md-4">
									<%= check_box("ben_id",c.id, {checked: false}) %>
									<%=h c.title%>
								</div>
							<% end %>
						</div>
					</div>
				</div>
			</div>
		<div class="container mb-2">
			<a class="btn-col" data-toggle="collapse" href="#iga" role="button" aria-expanded="false" aria-controls="collapseExample">
				IGA(institution gouvernemental associé)
			</a>
			<div class="collapse" id="iga">
				<div class="card card-body">
					<div class="row">
						<% Iga.all.each do |c| %>
							<div class="col-md-12">
								<%= check_box("iga_id",c.id, {checked: false}) %>
								<%=h c.title%>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="container mb-2">
			<a class="btn-col" data-toggle="collapse" href="#zi" role="button" aria-expanded="false" aria-controls="collapseExample">
				Région
			</a>
			<div class="collapse" id="zi">
				<div class="card card-body">
					<div class="row">
						<% Zone.all.each do |c| %>
							<div class="col-md-4">
								<%= check_box("zone_id",c.id, {checked: false}) %>
								<%=h c.title%>
							</div>
						<% end %>
					</div>
				</div>
			</div>
		</div>
		<div class="container mt-4">
			<input type="submit" value="Créer" class="sc-eerKOB cfnPHQ">
		</div>
	<% end %>
</div>

app/views/projets/search.html.erb
search.html.erb

app/views/projets/show.html.erb
<header class="aci59a-0 eyAIuG sticky-limit">
    <div class="sc-1gnwgfb-2 hVIPFV pict">
      <style type="text/css">
        .pict {
          <%if @projet.secteurprojets.count == 1%>
            <%@projet.secteurprojets.each do|sp|%>
              background-image: url('/<%=sp.secteur.image_url%>');
            <%end%>
          <%else%>
            background-image: url('/secteur/accueil.jpg');
          <%end%>
        }

      </style>  
    </div>
</header>
  <div class="logo">
    <div class="pic">
      <div class="imge-rep d-flex align-items-center justify-content-center">
        <%if @projet.ptf.image_url%>
          <img src="/<%= @projet.ptf.image_url%>" >
        <%end%>
      </div>
    </div>
    <div class="d-flex align-items-center h-text">
      <div class="text-white pr-4">
        <h3><%=@projet.nom_du_projet%></h3>
      </div>
    </div>
    <div class="asi"> 
      <div class="aside">
          <% if  @projet.secteurprojets.count == 1%>
              <p><span class="attr">Secteur : </span>
          <%else%>
              <p><span class="attr">Secteurs : </span>
          <%end%>
            <span class="word">
              <%@projet.secteurprojets .each do|sp|%>
                  <% if sp == @projet.secteurprojets.last%>
                    <span><%=sp.secteur.title %></span>
                  <% else %>
                    <span><%=sp.secteur.title %>, </span>
                  <% end %>
              <% end %>
              
            </span>
          </p>
       
          <% if  @projet.formeprojets.count == 1%>
              <p><span class="attr">Forme d'appui : </span>
          <%else%>
              <p><span class="attr">Formes d'appui : </span>
          <%end%>
          <span class="word">
              <%@projet.formeprojets .each do|fop|%>
                <% if fop == @projet.formeprojets.last%>
                  <span><%=fop.forme.title %></span>
                <% else %>
                  <span><%=fop.forme.title %>, </span>
                <% end %>
              <% end %>
            
          </span>
          </p>

          <% if  @projet.filiereprojets.count == 1%>
              <p><span class="attr">Filière : </span>
          <%else%>
              <p><span class="attr">Filières : </span>
          <%end%>
          <span class="word">
              <%@projet.filiereprojets .each do|fp|%>
                <% if fp == @projet.filiereprojets.last%>
                  <span><%=fp.filiere.title %></span>
                <% else %>
                  <span><%=fp.filiere.title %>, </span>
                <% end %>
              <% end %>
            
          </span>
          </p>
      </div>
    </div>
  </div>
  <div class="show-cont pt-4 pb-4">
    <div class="objectif mx-auto">
      <h2 class="text-left color">Objectif général du projet</h2>
      <div class="mt-2 pt-2">
        <%= raw @projet.objectif_generale_du_projet%>
      </div>
      <div class="appui mt-4">
        <h2 class="color text-left">Appui spécifique au secteur privé</h2>
        <div class="p-2">
          <%= raw @projet.aspsp%>
        </div>
      </div>
      <div class="row pt-4 pb-4">
        <div class="col-md-6 list">

          <% if  @projet.igaprojets.count == 1%>
              <p><span class="attr">Institution Gouvernementale Associée : </span></p>
          <%else%>
              <p><span class="attr">Institutions Gouvernementales Associées : </span></p>
          <%end%>
          <div class="mb-3">
              <%@projet.igaprojets .each do|g|%>
                  <%if g == @projet.igaprojets.last%>
                    <span><%=g.iga.title %></span>
                  <% else %>
                    <span><%=g.iga.title %>, </span>
                  <% end %>
              <% end %>
          </div>

          <% if  @projet.zoneprojets.count == 1%>
              <p><span class="attr">Région : </span></p>
          <%else%>
              <p><span class="attr">Régions : </span></p>
          <%end%>
          <div class="mb-3">
              <%@projet.zoneprojets .each do|zp|%>
                <% if zp == @projet.zoneprojets.last%>
                  <span><%=zp.zone.title %></span>
                <%else%>
                  <span><%=zp.zone.title %>, </span>
                <% end %>
              <% end %>
          </div>
          
          <% if  @projet.partenaireprojets.count == 1%>
              <p><span class="attr">Partenaire d'implémentation : </span></p>
          <%else%>
              <p><span class="attr">Partenaires d'implémentations : </span></p>
          <%end%>
          <div class="mb-3">
              <%@projet.partenaireprojets .each do|pap|%>
                <% if pap == @projet.partenaireprojets.last%>
                  <span><%=pap.partenaire.plateforme %></span>
                <%else%>
                  <span><%=pap.partenaire.plateforme %>, </span>
                <% end %>
              <% end %>
          </div>


          <% if  @projet.benefprojets.count == 1%>
              <p><span class="attr">Bénéficiaire : </span></p>
          <%else%>
              <p><span class="attr">Bénéficiaires : </span></p>
          <%end%>
          <div class="mb-3">
              <%@projet.benefprojets .each do|ben|%>
                  <%if ben == @projet.benefprojets.last%>
                    <span><%=ben.beneficiaire.title %></span>
                  <% else %>
                    <span><%=ben.beneficiaire.title %>, </span>
                  <% end %>
              <% end %>
          </div>

          <% @projet.montants.each do |m|%>
            <p><span class="attr">Montant  pour le secteur <%= m.secteur.title.downcase%> :</span>
                <p class="mb-3"><%= m.price %> <%= m.unite.nom%></p>
            </p>

          <%end%>
        </div>
        <div class="col-md-6 list">
          <p class="mb-3"><span class="attr">Nature de l'appui : </span><%=@projet.appui.title%></p>
          <p class="mb-3"><span class="attr">Début : </span><%=@projet.debut_du_projet%> &nbsp;&nbsp;&nbsp;&nbsp;<span class="attr">Fin : </span><%=@projet.fin%></p>
          <p><span class="attr">Alignement aux priorités du Plan Emergence de Madagascar : </span><p>
          <div class="mb-3">
            <% @projet.pemprojets.each do |p|%>
              <p> <%=p.pem.title%></p>
            <%end%>
          </div>
          <%if @projet.siteweb == " "%>
            <p class="mb-3"><span class="attr">Site web : </span>
                <span class="word">
                  <a href="https://<%= @projet.siteweb.remove('https://')%>"><%= @projet.siteweb%></a>
                </span>
            </p>
          <%end%>

          <%if @projet.files.attached?%>
            <%@projet.files.each do|file|%> 
              <p><span class="attr">Fichier : </span><%= link_to file.filename, rails_blob_path(file, disposition: "attachement") %></p>
            <%end%>
          <%end%>
       
        </div>
      </div>
    <div class="text-right">
      <%= link_to "Télécharger", projet_path(format: :pdf), :class => "sc-eerKOB cfnPHQ bold sear",  target: 'blank'%>
    </div>