config/routes.rb
Rails.application.routes.draw do
 

    resources :actus
    resources :apropos
    resources :contacts
    resources :publications

    	namespace :admin do
	  	resources :projets
	  	resources :users
      resources :publications

    end
 # 	resources :secteur
 # 	resources :pft
 #  resources :filiere

 	  namespace :super_admin do
      resources :publications
	    resources :users 
	    resources :projets
      resources :actus
      resources :tarifs
  	end
    
   root to: 'home#index'
   devise_for :users
   resources :projets
   get '/search' => 'projets#search', :as => 'search_projet'

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tarif.rb
class Tarif < ApplicationRecord
	belongs_to :unite
end

app/controllers/super_admin/actus_controller.rb
class SuperAdmin::ActusController < ApplicationController
  before_action :authenticate_user!

  def create

      @user = User.where(is_super_admin: true)
      @actu = Actu.create!(title: params[:title], user_id: current_user.id)

      if @actu.save
       @actu.files.attach(params[:files])
       redirect_to super_admin_actus_path, success: "Actualité créée avec succès"
     else
       render :new

     end 


  end

  def new
    @actus = Actu.order(:id).page(params[:page]).per(9)
  end

  def index
    @actus = Actu.order(:id).page(params[:page]).per(9)
  end

   def show
     @actu = Actu.find(params[:id])
   end

   def edit
     @actu = Actu.find(params[:id])
   end

  def update
      @actu = Actu.find(params[:id])
      if @actu.update(title: params[:title], user_id: current_user.id)
       redirect_to super_admin_actus_path, succès: "Modification terminée"
     end
  end

  def destroy
    @actu = Actu.find(params[:id])
    @actu.destroy
    redirect_to super_admin_actus_path
  end

end

app/controllers/super_admin/projets_controller.rb
class SuperAdmin::ProjetsController < ApplicationController
    before_action :authenticate_user!
    before_action :check_if_super_admin

  def index
  	@projets = Projet.where(validation: false).order(:id).page(params[:page]).per(9)
    @projets_valides = Projet.where(validation: true).order(:id).page(params[:page]).per(9)
  end

  def show
    @projet = Projet.find(params[:id])
  end

  def update
  	@projet = Projet.find(params[:id])
   	@projet.update(validation: true)
   	redirect_to super_admin_projets_path, success: "Projet validé"
  end

  def destroy
  	@projet = Projet.find(params[:id])
  	@projet.destroy
  	redirect_to super_admin_projets_path
  end

  def check_if_super_admin
      if current_user.is_super_admin == false
        redirect_to root_path
      end
  end
end

app/controllers/super_admin/publications_controller.rb
class SuperAdmin::PublicationsController < ApplicationController
	before_action :authenticate_user!

	def create
	  	@pub = Publication.create!(title: params[:title], description: params[:description], user_id: current_user.id)

	    	if @pub.save
	    		@pub.files.attach(params[:files])
	            redirect_to publications_path, success: "Publication créée avec succès"
	        else
	            render :new

	        end  
	end
	def edit
	   @pub = Publication.find(params[:id]) 	
	end    
	def update
		@pub = Publication.find(params[:id])

    	if @pub.update(title: params[:title], description: params[:description],user_id: current_user.id)
       		redirect_to super_admin_publications_path, success: "Modification terminéé"
	   	end
		
	end 
	def destroy
	  @pub = Publication.find(params[:id])
	  @pub.destroy
	  redirect_to super_admin_publications_path
		
	end
	def index
		@pubs = Publication.order(:id).page(params[:page]).per(9)
	end
	def show
		@pub = Publication.find(params[:id])
		
	end
end

app/controllers/super_admin/tarifs_controller.rb
class SuperAdmin::TarifsController < ApplicationController
	before_action :authenticate_user!
  def index
  end

  def edit
    @tarif = Tarif.find(params[:id])
  end

  def update
      @tarif = Tarif.find(params[:id])
      if @tarif.update(reference: params[:reference], valeur: params[:valeur], unite_id: params[:unite])

        if params[:cree] == 'À utiliser'
          @tarif.update(utilise: true)

        end
        redirect_to edit_super_admin_tarif_path(@tarif.id), success: "Taux de change modifié!!"
      else
        render :new

      end  
  end

  def new
  	@tarif = Tarif.new
  end

  def create
	  	@tarif = Tarif.create!(reference: params[:reference], valeur: params[:valeur], unite_id: params[:unite])
        if params[:cree] == 'A utiliser'
          @tarif.update(utilise: true)

        end
		  if @tarif.save
		    redirect_to new_super_admin_tarif_path, success: "Taux de change créé!!"
		  else
		    render :new

		  end  
  end

  def destroy
    @tarif = Tarif.find(params[:id])
      @tarif.destroy
    redirect_to super_admin_tarifs_path, danger:"Taux supprimé"
  end

end

app/controllers/super_admin/users_controller.rb
class SuperAdmin::UsersController < ApplicationController
 	before_action :authenticate_user!
	before_action :check_if_super_admin


	def index
		@users = User.where(is_admin: true).or(User.where(is_consultant: true))
		@users_en_attente = User.where(is_consultant: false,is_super_admin: false,is_admin: nil)
		
		@users.each do |u|
			@u = u
			u.messages.each do |m|
				@message_id = m.id
			end
		end	
	end


	def show
		@user = User.find(params[:id])
	end

	def check_if_super_admin
	    if current_user.is_super_admin == false
	      redirect_to root_path
	    end
 	end

 	

 	def update
 		@user = User.find(params[:id])
 		if buttonparams == 'Consultant'
 			@user.update(is_consultant: true)
 		else
 			@user.update(is_admin: true)
 		end

 		# if @user.is_consultant == false
 		# 	@user.update(is_consultant: true)
 		# if @user.is_admin == false
 		# 	@user.update(is_admin: true)
 		# end
 		redirect_to super_admin_users_path
 	end

 	def destroy
 		@user = User.find(params[:id])
 		@messages = Message.where(sender_id: @user.id)
 		@projets = Projet.where(bailleur_id: @user.id)
 		@publications = Publication.where(user_id: @user.id)
 		@user.destroy
 		
 		redirect_to super_admin_users_path
 	end

 	private 

 	def buttonparams
 		params[:valider]
 	end
end

app/helpers/super_admin/actus_helper.rb
module SuperAdmin::ActusHelper
end

app/helpers/super_admin/projets_helper.rb
module SuperAdmin::ProjetsHelper
end

app/helpers/super_admin/tarifs_helper.rb
module SuperAdmin::TarifsHelper
end

app/helpers/super_admin/users_helper.rb
module SuperAdmin::UsersHelper
end

app/views/super_admin/tarifs/edit.html.erb
<div class="container-actu mx-auto row mb-5 sans-head">
	<div class="col-md-4 border-right">
		<h5 class="mb-4 text-center">Modifier le taux de change n° <%= @tarif.id%></h5>
		<%= form_tag url_for(action: 'update'),method:'put', class:'form', multipart: true do%>
			<div class="mb-4">
				<label for="nom" class="mr-2 table">Unité de référence </label>
				<input type="text" name="reference" id="nom" value="<%= @tarif.reference%>" class="form-control" required="true">
			</div>
			<div class="mb-4">
				<label for="nom" class="mr-2 table"> Valeur </label>
				<input type="text" name="valeur" id="nom" value="<%= @tarif.valeur%>" class="form-control" required="true">
			</div>
			<div class="mb-4">				
				<select name="unite" class="form-control">
						<%Unite.all.each do |u|%>
							<%if u == @tarif.unite%>
								<option value="<%= @tarif.unite.id%>" selected><%= @tarif.unite.nom%></option>
							<%else%>
								<option value="<%= u.id%>"><%= u.nom%></option>
							<%end%>
						<%end%>
						</select>
			</div>
			<div class="mb-4">
				<% if @tarif.utilise == true%>
					<input type="submit" name="cree" value="Changer" class="btn btn-bg-primary rounded-0 text-white btn-lg btn-block">
				<%else%>
					<input type="submit" name="cree" value="À utiliser" class="btn btn-bg-primary rounded-0 text-white btn-lg btn-block">
					<input type="submit" name="cree" value="Changer" class="btn btn-bg-primary rounded-0 text-white btn-lg btn-block">
				<%end%>
			</div>
		<%end%>
	</div>
	<div class="col-md">
		<h5 class="mb-4 text-center">Taux de change</h5>
	    <% Tarif.all.order(id: :desc).each do |t|%>
		    <div class="row align-items-center no-gutters border-bottom pb-2 pt-2">
			    <div class="col-md-11 truncate-actu">
			    	<%= t.reference %> 
			    </div>
			     <div class="col-md-11 truncate-actu">
			    	<%= t.valeur %> 
			    </div>
			     <div class="col-md-11 truncate-actu">
			    	<%= t.unite.nom %> 
			    </div>
			    	<div class="col-md-11 truncate-actu">
		    	<% if t.utilise == true%>
				    	Cours de changer à utiliser de l'année <%= t.created_at.year%>
				<%else%>
			    	<a href="<%= edit_super_admin_tarif_path(t.id)%>" class="btn btn-success">A utiliser</a>
			    <%end%>
			    	<a href="<%= super_admin_tarif_path(t.id)%>" class="btn btn-danger" data-method="delete" data-confirm="Voulez-vous enlever ce taux ?">Suprrimer</a>
			    </div>
			    <div class="col-md-1 text-center">
			    	<a href="<%= edit_super_admin_tarif_path(t.id)%>" class="table">Changer</a>
			    </div>
		    </div>
		<%end%>	
	</div>
</div>

app/views/super_admin/tarifs/index.html.erb
<h1>SuperAdmin::Tarifs#index</h1>
<p>Find me in app/views/super_admin/tarifs/index.html.erb</p>

app/views/super_admin/tarifs/new.html.erb
<div class="container-actu mx-auto row mb-5 sans-head">
	<div class="col-md-4 border-right">
		<h5 class="mb-4 text-center">Créer taux de change</h5>
		<%= form_tag url_for(action: 'create'),method:'post', class:'form', multipart: true do%>
			<div class="mb-4">
				<label for="nom" class="mr-2 table">Unité de référence </label>
				<input type="text" name="reference" id="nom" placeholder="UAC/EURO/USD/MGA" class="form-control" required="true">
			</div>
			<div class="mb-4">
				<label for="nom" class="mr-2 table"> Valeur </label>
				<input type="text" name="valeur" id="nom" placeholder="1.456" class="form-control" required="true">
			</div>
			<div class="mb-4">				
				<%= select_tag 'unite', options_for_select(Unite.all.order(:nom).collect{ |c| [c.nom, c.id] }), :include_blank => "choisir", class: "form-control", required: true%>
			</div>
			<div class="mb-4">
				<input type="submit" name="cree" value="Enregistrer" class="btn btn-bg-primary rounded-0 text-white btn-block">
				<input type="submit" name="cree" value="À utiliser" class="btn btn-bg-primary rounded-0 text-white btn-block">
			</div>
		<%end%>
	</div>
	<div class="col-md">
		<h5 class="mb-4 text-center">Taux de change</h5>
	    <% Tarif.all.order(id: :desc).each do |t|%>
		    <div class="row align-items-center no-gutters border-bottom pb-2 pt-2">
			    <div class="col-md-11 truncate-actu">
			    	<%= t.reference %> 
			    </div>
			     <div class="col-md-11 truncate-actu">
			    	<%= t.valeur %> 
			    </div>
			    <div class="col-md-11 truncate-actu">
			    	<%= t.unite.nom %> 
			    </div>
			    	<div class="col-md-11 truncate-actu">
		    	<% if t.utilise == true%>
				    	Cours de changer à utiliser de l'année <%= t.created_at.year%>
				    
			    <%else%>
			    		<a href="<%= edit_super_admin_tarif_path(t.id)%>" class="btn btn-success">A utiliser</a>
			    	
			    <%end%>
			    	<a href="<%= super_admin_tarif_path(t.id)%>" class="btn btn-danger" data-method="delete" data-confirm="Voulez-vous enlever ce taux ?">Suprrimer</a>
			    </div>
			    <div class="col-md-1 text-center">
			    	<a href="<%= edit_super_admin_tarif_path(t.id)%>" class="table">Changer</a>
			    </div>
		    </div>
		<%end%>	
	</div>
</div>

app/views/super_admin/tarifs/update.html.erb
<h1>SuperAdmin::Tarifs#update</h1>
<p>Find me in app/views/super_admin/tarifs/update.html.erb</p>