config/routes.rb
Rails.application.routes.draw do
 

    resources :actus
    resources :apropos
    resources :contacts
    resources :publications

    	namespace :admin do
	  	resources :projets
	  	resources :users
      resources :publications

    end
 # 	resources :secteur
 # 	resources :pft
 #  resources :filiere

 	  namespace :super_admin do
      resources :publications
	    resources :users 
	    resources :projets
      resources :actus
      resources :tarifs
  	end
    
   root to: 'home#index'
   devise_for :users
   resources :projets
   get '/search' => 'projets#search', :as => 'search_projet'

   # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/actu.rb
class Actu < ApplicationRecord

	has_many_attached :files
	belongs_to :user
end

app/models/appui.rb
class Appui < ApplicationRecord
	has_many :projets
end

app/models/change.rb
class Change < ApplicationRecord
	belongs_to :unite
end

app/models/engagement.rb
class Engagement < ApplicationRecord
	has_many :pems
end

app/models/filiere.rb
class Filiere < ApplicationRecord
	has_many :filiereprojets
	has_many :projets, through: :filiereprojets

	has_many :secteur_filieres
	has_many :secteurs, through: :secteur_filieres
end

app/models/forme.rb
class Forme < ApplicationRecord
	has_many :formesecteurs
	has_many :secteurs, through: :formesecteurs

	has_many :formeprojets
	has_many :projets, through: :formeprojets
end

app/models/iga.rb
class Iga < ApplicationRecord
	has_many :Igaprojets
	has_many :projets, through: :Igaprojets
	has_many :users
	has_many :users, through: :organismes
end

app/models/igaprojet.rb
class Igaprojet < ApplicationRecord
	belongs_to :iga
	belongs_to :projet
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: 'User'
	belongs_to :admin, class_name: 'User'

end

app/models/montant.rb
class Montant < ApplicationRecord
	belongs_to :projet
	belongs_to :unite
	belongs_to :secteur

end

app/models/organisme.rb
class Organisme < ApplicationRecord
	belongs_to :ptf, optional: true
	belongs_to :iga, optional: true
	belongs_to :user

end

app/models/pem.rb
class Pem < ApplicationRecord
	belongs_to :engagement

	has_many :pemprojets
	has_many :projets, through: :pemprojets

end

app/models/pemprojet.rb
class Pemprojet < ApplicationRecord
	belongs_to :projet
	belongs_to :pem
end

app/models/projet.rb
class Projet < ApplicationRecord
        validates :objectif_generale_du_projet, presence: true
        validates :aspsp, presence: true
        
        belongs_to :bailleur, optional: true, class_name: 'User'
        belongs_to :ptf, optional: true
        belongs_to :appui, optional: true
        has_many :montants
# relation de table entre projet et secteur a travers benefprojet
        has_many :benefprojets
        has_many :beneficiaires, through: :benefprojets
   
# relation de table entre projet et secteur a travers zoneprojet
        has_many :zoneprojets
        has_many :zones, through: :zoneprojets
       
        # relation de table entre projet et secteur a travers igaprojets
        has_many :igaprojets
        has_many :igas, through: :igaprojets
      
     # relation de table entre projet et secteur a travers filiereprojets
        has_many :filiereprojets
        has_many :filieres, through: :filiereprojets
        

        # relation de table entre projet et secteur a travers secteurprojet

        has_many :secteurprojets 
        has_many :secteurs, through: :secteurprojets
    

        has_many :pemprojets
        has_many :pems, through: :pemprojets

        has_many :formeprojets
        has_many :formes, through: :formeprojets

        has_many :partenaireprojets
        has_many :partenaires, through: :partenaireprojets
    
        
        has_many_attached :files
        has_one_attached :picture
       

        after_create :create_project_send

        # This method calls the order_email method from user_mailer, passing the order as an argument
        def create_project_send
            UserMailer.create_project_email(self).deliver_now
        end

end

app/models/ptf.rb
class Ptf < ApplicationRecord
	has_many :projets
	has_many :users
	has_many :users, through: :organismes
end

app/models/publication.rb
class Publication < ApplicationRecord

	  has_many_attached :files
	  belongs_to :user
end

app/models/secteur.rb
class Secteur < ApplicationRecord
	has_many :secteurprojets 
	has_many :projets, through: :secteurprojets

	has_many :secteur_filieres
	has_many :filieres, through: :secteur_filieres

	has_many :formesecteurs
	has_many :formes, through: :formesecteurs
	
	has_many :montants


end

app/models/tarif.rb
class Tarif < ApplicationRecord
	belongs_to :unite
end

app/models/unite.rb
class Unite < ApplicationRecord
	has_many :montants
	has_many :tarifs
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
   has_many :projets, foreign_key: 'bailleur_id'
   has_many :actus, foreign_key: 'user_id'
   has_many :publications, foreign_key: 'bailleur_id'
   has_many :publications, foreign_key: 'user_id'
   has_many :messages, foreign_key: 'sender_id'

   after_create :update_admin, :welcome_send

    def welcome_send
      UserMailer.welcome_email(self).deliver_now
    end
    
	  def update_admin
	  	@user = User.last
	    if @user.is_admin == true
	    	@user.update(is_admin: nil)
	    end
	  end

	has_one :organisme


end

app/models/zone.rb
class Zone < ApplicationRecord
	has_many :zoneprojets
	has_many :projets, through: :zoneprojets
end

app/controllers/admin/publications_controller.rb
class Admin::PublicationsController < ApplicationController
	before_action :authenticate_user!
	def index
		@pubs = Publication.where(user_id: current_user.id)
	end
	def create
			@pub = Publication.create!(title: params[:title], description: params[:description], user_id: current_user.id)

	    	if @pub.save
	    		@pub.files.attach(params[:files])
	            redirect_to publications_path, success: "Publication créée"
	        else
	            render :new

	        end  

	end
	def edit
		@pub = Publication.find(params[:id])
	end
	def update
    @pub = Actu.find(params[:id])

    if @pub.update(title: params[:title], description: params[:description],user_id: current_user.id)
       redirect_to admin_publications_path, success: "Modification terminée"
	   end
	end
	def show
		@pub = Publication.find(params[:id])
	end

	def destroy
	  @pub = Publication.find(params[:id])
	  @pub.destroy
	  redirect_to admin_publications_path
	end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :authenticate_user!
  def index
  	@pubs = Publication.order(:id).page(params[:page]).per(9)
  end

  def new

  end

  
  	
  def show
  	@pub = Publication.find(params[:id])
  end

  def update
  end
end

app/controllers/super_admin/publications_controller.rb
class SuperAdmin::PublicationsController < ApplicationController
	before_action :authenticate_user!

	def create
	  	@pub = Publication.create!(title: params[:title], description: params[:description], user_id: current_user.id)

	    	if @pub.save
	    		@pub.files.attach(params[:files])
	            redirect_to publications_path, success: "Publication créée avec succès"
	        else
	            render :new

	        end  
	end
	def edit
	   @pub = Publication.find(params[:id]) 	
	end    
	def update
		@pub = Publication.find(params[:id])

    	if @pub.update(title: params[:title], description: params[:description],user_id: current_user.id)
       		redirect_to super_admin_publications_path, success: "Modification terminéé"
	   	end
		
	end 
	def destroy
	  @pub = Publication.find(params[:id])
	  @pub.destroy
	  redirect_to super_admin_publications_path
		
	end
	def index
		@pubs = Publication.order(:id).page(params[:page]).per(9)
	end
	def show
		@pub = Publication.find(params[:id])
		
	end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/admin/publications/edit.html.erb
<%= form_tag url_for(action: 'update'),method:'put', class:'form', multipart: true do%>

	<div class="container sans-head">
			<div class=" row mb-2">
				<div class="col-6">
					<div>
						<label for="nom" class="mr-2 table">Titre </label>
					</div>
					<input type="text" name="title" id="nom" placeholder="title" class="form-control" required="true" value="<%=@pub.title%>">
				</div>
				<div class="col-6">
					<div>
						<label for="nom" class="mr-2 table">Titre </label>
					</div>
					<input type="text" name="description" id="nom" placeholder="title" class="form-control" required="true" value="<%=@pub.description%>">
				</div>
			</div>
		</div>

	<div class="container mb-2 mt-4">
			<span class="mr-2 table">Documents :</span>
	
			<p><%= file_field_tag :files, name: "files[]", required: true, multiple: true %></p> <br>
			<p><input type="submit" name="cree" value="Publier" class="sc-eerKOB cfnPHQ"></p>
		
	</div>		
<%end%>

app/views/admin/publications/index.html.erb
<div class="container sans-head">
		<div class="mb-4">
		<h3 style="color: #52c39b; text-align: center;">Mes publications</h3>
		</div>
	<div class="row justify-content-center">
		<% @pubs.each do |p|%>
			<div class="col-md-4 card mx-1 position-relative ">
				<div class="card-body">
					 	 	<div class="card-title">
						    <h5 class="primary-color"><%= p.title %></h5>
						    </div>
						<div class="card-text">
							<p class="card-text text-muted mb-5 truncate-pub"><%= p.description %></p>
						</div>
						<p class="mt-3 position-absolute more-info-pub"><a href="<%= admin_publication_path(p.id)%>" class="btn-forgot underline">Voir</a></p>
				</div>
			</div>
      <%end%>
	</div>
</div>

app/views/admin/publications/new.html.erb
<%= form_tag url_for(action: 'create'),method:'post', class:'form', multipart: true do%>
	<div class="container sans-head border rounded p-4">
		<h5 class="text-center">Créer votre publication</h5>
		<div class="mb-2">
			<label for="nom" class="table">Titre </label>
			<input type="text" name="title" id="nom" placeholder="title" class="form-control" required="true">
		</div>
		<div class="mb-2">
			<label for="nom" class="table">Description </label>
			<textarea type="text" name="description" id="nom" placeholder="description" class="form-control p-2" rows="5" required="true"></textarea>
		</div>
			<div class="mb-2 mt-4">
				<%= file_field_tag :files, name:"files[]", required: true, multiple: true, id: :"document", class: 'toggleclass'%>
				<span class="btn btn-secondary" id="simulateur">Ajouter des fichiers liés au publication</span>
			</div>
		<div>
			<input type="submit" name="cree" value="Publier" class="btn btn-bg-primary rounded-0 text-white btn-lg btn-block mt-4">
		</div>
	</div>
<%end%>

app/views/admin/publications/show.html.erb
<div class="container sans-head" >
	<div class="titre">
	<h5><%=@pub.title%></h5>
   </div>
   <div>
		<div class="mt-3">
			<p class="text-muted mt-3 mb-3 text-justify"><%=@pub.description%></p>
			<%if @pub.files.attached?%>
				<h5>Liste des documents associés :</h5>
				<ol class="ml-4">
					<%@pub.files.all.each do|file|%> 
						<li class="mb-3 mt-3"><%= link_to file.filename, rails_blob_path(file, disposition: "attachement"), class: "doc-relative ml-2" %></li>
					<%end%>
				</ol>
			<%end%>
		</div>
	 	<div class="text-left mt-4">
	      <a href="<%=  edit_admin_publication_path(@pub.id)%>" class="sc-eerKOB cfnPHQ bold sear" >Modifier</a>
	      <a href="<%= admin_publication_path(@pub.id)%>" class="btn btn-danger"  data-method="delete" data-confirm="Voulez-vous supprimer cette publication?"> Supprimer</a>
	    </div>
	</div>
</div>
<%= render partial: "/super_admin/confirm.html.erb"%>

app/views/publications/index.html.erb
<div class="sans-head mb-5">
	<div class="mb-4">
		<h3 style="color: #52c39b; margin: 3%; text-align: center;" >Toutes les publications</h3>
		</div>
	<div class="row justify-content-center w-100">
		<% @pubs.each do |p|%>
			<div class="col-md-3 card mx-1 mb-2 position-relative">
				<div class="card-body">
					 	 	<div class="card-title">
						    <h5 class="primary-color"><%= p.title %></h5>
						    </div>
						<div class="card-text">
							<p class="card-text text-muted mb-5 truncate-pub"><%= p.description %></p>
						</div>
						<p class="mt-3 position-absolute more-info-pub"><a href="<%= publication_path(p.id)%>" class="btn-forgot underline">Voir</a></p>
				</div>
			</div>
      <%end%>
	</div>
	<div class="text-center">
		<%= paginate @pubs %>
	</div>
</div>

app/views/publications/show.html.erb
<div class="container sans-head" >
	<div class="titre">
	<h5><%=@pub.title%></h5>
   </div>
   <div>
		<div class="mt-3">
			<p class="text-muted mt-3 mb-3 text-justify"><%=@pub.description%></p>
			<%if @pub.files.attached?%>
				<h5>Liste des documents associés :</h5>
				<ol class="ml-4">
					<%@pub.files.all.each do|file|%> 
						<li class="mb-3 mt-3"><%= link_to file.filename, rails_blob_path(file, disposition: "attachement"), class: "doc-relative ml-2" %></li>
					<%end%>
				</ol>
			<%end%>
		</div>
	</div>
</div>